version: '3'
 
services:

  red:
    #image: nodered/node-red-docker:0.19.5-slim
    build:
      context: ./node-red/
    volumes:
      - ./node-red:/data
    ports:
      - 1880:1880
    working_dir: /data/
    command: "npm start"

  mqtt:
    image: eclipse-mosquitto
    ports: 
      - 1883:1883
      - 9001:9001


  influx:
    image: influxdb
    volumes:
      - ./influx:/var/lib/influxdb
    ports:
      - 8086:8086   

  util:
    build: 
      context: ./util
    volumes: 
      - ./node-red:/data
      - ./util/:/util
    working_dir: /util
    command: bash
    #entrypoint: sh -c '/stubout.sh'

